name: f2p_games
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

  # UI and design
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  card_swiper: ^3.0.1
  lottie: ^3.3.2
  gradient_borders: ^1.0.0
  shimmer_animation: ^2.2.0
  eva_icons_flutter: ^3.1.0

  # Firebase
  firebase_core: ^2.25.0
  firebase_auth: ^4.11.0
  firebase_analytics: ^10.1.0

  # Google
  google_sign_in: ^7.2.0

  # Image and color utilities
  cached_network_image: ^3.4.1
  palette_generator: ^0.3.3
  flutter_dominant_color_container: ^1.0.0

  # Splash screen
  flutter_native_splash: ^2.4.7
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
